export { default as authRouter } from "./auth.route";
export { default as categoryRouter } from "./category.route";
export { default as favoriteRouter } from "./favorite.route";
export { default as fileRouter } from "./file.route";
export { default as orderRouter } from "./order.route";
export { default as productRouter } from "./product.route";
export { default as promotionRouter } from "./promotion.route";
export { default as userAddressRouter } from "./user-address.route";
export { default as userRouter } from "./user.route";
